# -*- conf -*-

[main]
font=JetBrainsMonoNerdFontMono:size=11
letter-spacing=0.5
dpi-aware=yes
line-height=25px
pad=15x15
letter-spacing=0

include=/usr/share/foot/themes/tempus-winter

[cursor]
style=beam
blink=yes

[mouse]
hide-when-typing=yes

[colors-dark]


alpha=0.94

#background=1b1b1b
#foreground=a9a9a9
#regular0=353839   # Surface 1 (Black)
#regular1=fd0e35   # Red
#regular2=507d2a    # Green
#regular3=b78727   # Yellow
#regular4=4682b4   # Blue
#regular5=ba55d3   # Pink
#regular6=367588   # Teal
#regular7=d3d3d3   # Subtext 1 (White)

#[colors-light]
#bright0=353839    # Surface 2
#bright1=b22222    # Red
#bright2=355e3b    # Green
#bright3=b8860b   # Yellow
#bright4=5072a7    # Blue
#bright5=9932cc    # Pink
#bright6=49796b    # Teal
#bright7=dcdcdc    # Subtext 0
